### ISSUE TITLE
Does edge work with intraday data?

### ISSUE THREAD

**Issue by waynelapierre** [eguidotti/bidask#11]
Must the open, high, low, and close prices be daily?

**Comment by eguidotti** [comment]
The estimator works also with intraday data. Please refer to the paper https://doi.org/10.1016/j.jfineco.2024.103916

**Comment by waynelapierre** [comment]
I am working with one-minute OHLC data. For each day, I divide the observations into two groups, positive returns vs. negative returns. Does it make sense to use your package to calculate two bid-ask spreads for the day, one for the positive returns and the other for the negative returns? I know the Amihud illiquidity measure can be used this way, but not sure about your measure. Thanks.

**Comment by eguidotti** [comment]
Thanks for reaching out. No, that doesn't make sense because the OHLC prices must be subsequent so it is not possible to split the sample based on positive and negative returns. Hope this helps!

**Comment by waynelapierre** [comment]
thanks!
