### ISSUE TITLE
Vectorized python version

### ISSUE THREAD

**Issue by eguidotti** [eguidotti/bidask#12]
There seems to be increasing interest in a vectorized Python version that efficiently computes estimates based on rolling/expanding windows (https://github.com/eguidotti/bidask/pull/8 and https://github.com/eguidotti/bidask/issues/9).

A vectorized rolling implementation is available in R, which should provide a good starting point for a similar implementation in Python. See https://github.com/eguidotti/bidask/blob/main/r/R/edge.R 

Any help is greatly appreciated!

**Comment by joseortiz3** [comment]
I'll implement this in a PR today. Any special requests? I propose making the rolling vectorized python function a separate function from the current python function that is based on the pseudocode. Do you want a test, or anything else of note?

**Comment by eguidotti** [comment]
Sounds great! Yes, a separate function would be best at the moment. Also adding some tests to check consistency between the vectorized and non-vectorized versions would be very helpful

**Comment by joseortiz3** [comment]
I'm almost done, the only issue is that in `edge.py` there is:

```python
    if pt == 0 or po == 0 or pc == 0:
        return np.nan
```

Whereas the R code doesn't have any similar escape. I'm not sure yet of the best solution for the vectorized code to implement this sort of escape. It results in more NaNs for the rolling.apply-based method compared to the vectorized method when the rolling window size is <= 2. In those cases, the vectorized method gives spread estimates on the order of <1e-8. All other values are equal to numerical precision for any greater window size.

I will keep trying to match that escape condition in `edge.py`. Will share progress tonight.

**Comment by eguidotti** [comment]
The vectorized version is up and running! Release 2.1.0 on PyPI.

Thank you so much @joseortiz3; your work and feedback has been tremendously helpful! 🙏
