### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by tommedema** [eguidotti/bidask#4]
Reproducible code:

```python
import warnings
from bidask import edge

# treat warnings as errors
warnings.filterwarnings('error')

edge(
    np.array([18.21, 17.61, 17.61]),
    np.array([18.21, 17.61, 17.61]),
    np.array([17.61, 17.61, 17.61]),
    np.array([17.61, 17.61, 17.61])
)
```

<img width="898" alt="Screen Shot 2022-11-03 at 8 21 42 PM" src="https://user-images.githubusercontent.com/331833/199878085-2cfce078-d6c6-4d59-bc8f-52fe203c18d0.png">

**Comment by eguidotti** [comment]
Thanks! This is fixed in the new version (just updated on PyPI).
The function now returns `nan` when the variance is zero, as it should be.
