### ISSUE TITLE
From spread + observed price to estimated bid and ask prices

### ISSUE THREAD

**Issue by tommedema** [eguidotti/bidask#5]
This may seem obvious, but I just wanted to double check that the following is true:

If bidask's edge function returned 0.025, it means the estimated bidask spread is 2.5% of the observed price. If the observed price is $100, then the bidask spread is $100 * 0.025 = $2.5. Since bidask is the difference from ask to bid, assuming the observed price is in the middle, the observed price would therefore be half of the bidask from each of the two extremes.

I.e.:

Estimated bid = 100 - 2.5 / 2 = $98.75

Estimated ask = 100 + 2.5/2 = $101.25

Assuming that the observed price is in the middle of the bid - ask spread.

Is that correct? Specifically I want to double check that the ask is not 102.5 (100 * 2.5%) and the bid is not $97.5 (100 * (100-2.5%))

**Comment by tommedema** [comment]
Btw @eguidotti, I'm also noticing that in my data (20 years, real stock market data) when using the past 30 days (rolling window), 14% of data points have a spread >= 5%, and 6% >= 10% --- that seems really high? is it possible that spreads are indeed that high so frequently? e.g. AAAB on 2000-05-30 is reported to have a 10% avg spread in last 30 days:

```python
edge(
    np.array([5.893, 5.714, 6.429, 5.833, 5.833, 5.595, 5.476, 5.714, 5.714,
           5.655, 5.714, 6.369, 6.369, 6.369, 6.369, 6.012, 5.952, 6.667,
           6.667, 6.667, 6.667, 5.952, 5.714, 5.714, 5.714, 5.357, 6.071,
           5.833, 5.595, 6.548], dtype=np.float32),
    np.array([6.429, 5.893, 6.429, 6.071, 6.429, 6.429, 5.714, 5.714, 5.714,
           5.655, 6.19 , 6.369, 6.369, 6.369, 6.369, 6.667, 6.667, 6.667,
           6.667, 6.667, 6.667, 5.952, 5.714, 5.714, 5.714, 5.476, 6.19 ,
           5.952, 5.595, 6.548], dtype=np.float32),
    np.array([5.893, 5.714, 6.429, 5.833, 5.833, 5.595, 5.   , 5.714, 5.714,
           5.655, 5.714, 5.952, 6.369, 6.369, 5.833, 6.012, 5.952, 6.667,
           6.667, 6.667, 6.667, 5.476, 5.714, 5.714, 5.714, 5.357, 5.476,
           5.833, 5.595, 5.357], dtype=np.float32),
    np.array([6.429, 5.833, 6.429, 6.071, 6.429, 5.774, 5.476, 5.714, 5.714,
           5.655, 6.19 , 6.369, 6.369, 6.369, 6.369, 6.25 , 6.667, 6.667,
           6.667, 6.667, 6.667, 5.833, 5.714, 5.714, 5.714, 5.357, 5.476,
           5.952, 5.595, 5.655], dtype=np.float32)
) // 0.10667654584581966
```

When changing it to 60 days it becomes 0.08537814, still seems very high?

**Comment by eguidotti** [comment]
> Is that correct? Specifically I want to double check that the ask is not 102.5 (100 * 2.5%) and the bid is not $97.5 (100 * (100-2.5%))

That's correct!

> 14% of data points have a spread >= 5%, and 6% >= 10% --- that seems really high? 

That's quite possible. The **average** spread for "small" US stocks in early 2000 is 5% (see the [paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3892335), Figure 7). Here "small stocks" means the stocks with market capitalization below the median capitalization. Thus, for half the sample the spread is quite large. Of course, for the particular case of AAAB on 2000-05-30, it may also be the case that the estimate is affected by a large estimation error.

**Comment by tommedema** [comment]
Thanks so much!

**Comment by impredicative** [comment]
> Estimated bid = 100 - 2.5 / 2 = $98.75

To be pedantic, the bid must never be negative, so any negative values must be clipped by a user. If using `pandas`, `series_est_bid.clip(lower=0)` will ensure it.

**Comment by eguidotti** [comment]
@impredicative Yes, however the price should always be positive unless you estimate a spread above 200%. Moreover, as correctly stated by @tommedema, you can compute bids and asks only

> assuming the observed price is in the middle

which is rarely the case. I see this issue as a clarification question rather than a way to compute bids and asks.
