### ISSUE TITLE
Python bidask==0.1.1 doesn't support "sign"

### ISSUE THREAD

**Issue by impredicative** [eguidotti/bidask#6]
The [docs](https://github.com/eguidotti/bidask/tree/main/python) for the Python version of `bidask` mention `sign=False`. This kwargument however is not supported by the current latest version of `bidask` which is 0.1.1. The following exception occurs:

    TypeError: edge() got an unexpected keyword argument 'sign'

**Comment by eguidotti** [comment]
Yes, version 0.1.1 currently on [PyPI](https://pypi.org/project/bidask/) does not support the argument `sign`. 

All the implementations at this repo have been updated and now use a revised version of the estimator. I'll upload the new implementations on PyPI for Python and on CRAN for R as soon as I'll update the paper on SSRN. This is expected to happen soon. If you would like to use the new implementation now, please install the version that is on github. 

I'll keep this issue open and close it as soon as I'll release the new packages and paper. Thanks!

**Comment by eguidotti** [comment]
New preprint now available at [SSRN](https://ssrn.com/abstract=3892335)

Version 2.0.0 now available at [PyPI](https://pypi.org/project/bidask/)
