### ISSUE TITLE
vectorized version

### ISSUE THREAD

**Issue by ghost** [eguidotti/bidask#9]
Is that possible to get a vectorized python version?

**Comment by eguidotti** [comment]
What do you mean exactly? Maybe a function to compute rolling spreads as proposed in https://github.com/eguidotti/bidask/pull/8?

**Comment by ghost** [comment]
@eguidotti 
The `edge` procedure gets a list of open, high, low, close, and returns a number, right? the spread.
Imagine i want to do this to all the expending subsets of the list.
In other words, and efficient way do to that:
`[edge(open[:i], high[:i], close[:i], low[:i]) for i in range(len(open))]`

**Comment by eguidotti** [comment]
I prefer not to add complexity in the implementation here to maintain consistency with the implementations in other languages. ~Hopefully, your solution should already be fast enough~ Turns out this is not the case; I've opened https://github.com/eguidotti/bidask/issues/12
